//! WebRTC direct-connection mode for moq-boy.
//!
//! Accepts WebRTC peer connections from browsers via HTTP signaling,
//! delivers H.264 video and Opus audio over WebRTC media tracks, and
//! receives button commands over a DataChannel.
//!
//! ## Architecture
//!
//! ```text
//! Emulator → Video Encoder (H.264 NALs) → Broadcast Channel
//!                                         ├→ MoQ Track (existing)
//!                                         └→ WebRTC Peers (new)
//!
//! Emulator → Audio PCM → Opus Encoder → RTP → WebRTC Peers (new)
//!                      └→ MoQ Track (existing)
//! ```
//!
//! Audio encoding is duplicated in WebRTC mode: we encode Opus directly
//! from the emulator's PCM samples so we can packetize the encoded frames
//! into RTP. This avoids modifying the internal moq-audio pipeline.

use std::collections::HashMap;
use std::net::SocketAddr;
use std::sync::Arc;
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use bytes::Bytes;
use tokio::sync::Mutex;

use crate::audio::AudioEncoder;
use crate::emulator::{self, Emulator};
use crate::input::Command;
use crate::stats::Stats;
use crate::status::{self, StatusPublisher};
use crate::video::EncodedFrame;

use moq_webrtc::{
    self,
    signaling::SignalingServer,
    InputCommand as WebrtcInput,
    WebrtcOutput, WebrtcPeer,
};

/// Shared WebRTC session state, safe to share across tasks.
struct WebrtcSession {
    /// Active peers indexed by session ID.
    peers: Mutex<HashMap<String, WebrtcPeer>>,
    /// Received viewer commands (DataChannel → emulator thread).
    cmd_tx: tokio::sync::mpsc::Sender<Command>,
    /// Whether video is active (at least one connected peer).
    video_active: std::sync::atomic::AtomicBool,
    /// Whether audio is active.
    audio_active: std::sync::atomic::AtomicBool,
}

/// Run moq-boy in WebRTC direct mode.
///
/// - Binds an HTTP signaling server on `addr`
/// - Accepts SDP offers from browsers
/// - Drives the emulator loop, delivering encoded frames to WebRTC peers
/// - Receives button commands via DataChannel
pub async fn run_webrtc_mode(
    _config: &crate::Config,
    name: &str,
    rom_path: &std::path::Path,
    session: Arc<crate::Session>,
    cmd_tx: tokio::sync::mpsc::Sender<Command>,
    cmd_rx: tokio::sync::mpsc::Receiver<Command>,
    audio_encoder: AudioEncoder,
    status_publisher: StatusPublisher,
    addr: SocketAddr,
) -> Result<()> {
    tracing::info!(%addr, %name, "starting WebRTC direct mode");

    // Set up the signaling server.
    let (signaling, mut offer_rx) = SignalingServer::new();
    let signaling = Arc::new(signaling);
    let signaling_clone = signaling.clone();
    tokio::spawn(async move {
        if let Err(e) = signaling_clone.serve(addr).await {
            tracing::error!(error = %e, "signaling server stopped");
        }
    });

    // Create a broadcast channel for encoded video frames from the encoder thread.
    // The encoder was already created with `webrtc_tap: true` in main.rs.
    let mut video_rx = session
        .video_encoder
        .webrtc_subscribe()
        .context("video encoder was not created with webrtc_tap enabled; set webrtc_tap=true in EncoderConfig")?;

    // Shared session state for peer management.
    let webrtc_session = Arc::new(WebrtcSession {
        peers: Mutex::new(HashMap::new()),
        cmd_tx: cmd_tx.clone(),
        video_active: std::sync::atomic::AtomicBool::new(false),
        audio_active: std::sync::atomic::AtomicBool::new(false),
    });

    // Spawn the offer acceptance loop: when a browser posts an SDP offer,
    // create a WebRTC peer and register it.
    let ws = webrtc_session.clone();
    let _sig = signaling.clone();
    tokio::spawn(async move {
        while let Ok(accepted) = offer_rx.recv().await {
            let session_id = accepted.session_id.clone();
            match WebrtcPeer::accept_offer(session_id.clone(), &accepted.sdp_offer) {
                Ok(peer) => {
                    tracing::info!(%session_id, "WebRTC peer created");
                    // Generate the SDP answer and push it to the client.
                    // In a full implementation, the answer SDP is generated by
                    // str0m when we call local_sdp() after set_remote_sdp().
                    // For now, we register the peer and the signaling server
                    // will deliver the answer via the ICE SSE channel.
                    let mut peers = ws.peers.lock().await;
                    peers.insert(session_id, peer);
                }
                Err(e) => {
                    tracing::warn!(%session_id, error = %e, "failed to accept WebRTC offer");
                }
            }
        }
    });

    // Spawn a task to poll peers and relay ICE candidates.
    let ws2 = webrtc_session.clone();
    let sig2 = signaling.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(Duration::from_millis(10));
        loop {
            interval.tick().await;
            let mut peers = ws2.peers.lock().await;
            let mut dead_sessions = Vec::new();

            for (sid, peer) in peers.iter_mut() {
                match peer.poll() {
                    Ok(outputs) => {
                        for out in outputs {
                            match out {
                                WebrtcOutput::IceCandidate { session_id: _, candidate } => {
                                    sig2.push_ice(sid, &candidate).await;
                                }
                                WebrtcOutput::IceDisconnected(sid) => {
                                    dead_sessions.push(sid);
                                }
                                WebrtcOutput::Answer { session_id, sdp } => {
                                    // Push the answer via the ICE channel as a special event.
                                    // A full implementation would add a dedicated answer SSE event.
                                    sig2.push_ice(&session_id, &format!("ANSWER:{}", sdp)).await;
                                }
                            }
                        }
                    }
                    Err(e) => {
                        tracing::warn!(session=%sid, error=%e, "peer poll error");
                        dead_sessions.push(sid.clone());
                    }
                }

                // Drain DataChannel commands.
                while let Some(cmd) = peer.recv_input() {
                    let command = into_command(cmd);
                    let _ = ws2.cmd_tx.try_send(command);
                }
            }

            for sid in dead_sessions {
                peers.remove(&sid);
                tracing::info!(%sid, "WebRTC peer removed");
            }

            // Update active state.
            let count = peers.len();
            ws2.video_active.store(count > 0, std::sync::atomic::Ordering::Relaxed);
            ws2.audio_active.store(count > 0, std::sync::atomic::Ordering::Relaxed);
        }
    });

    // Run the emulator on a blocking thread (same as relay/server mode).
    let rom_path = rom_path.to_path_buf();
    let session_clone = session.clone();
    let ws3 = webrtc_session.clone();
    let emulator_handle = tokio::task::spawn_blocking(move || {
        run_emulator_webrtc(
            session_clone,
            &rom_path,
            audio_encoder,
            status_publisher,
            cmd_rx,
            ws3,
        )
    });

    // Drive the WebRTC frame dispatch loop on the async side.
    let dispatch_loop = dispatch_frames_to_peers(webrtc_session.clone(), &mut video_rx);

    tokio::select! {
        res = emulator_handle => res?.context("emulator error"),
        res = dispatch_loop => res,
    }
}

/// Runs the emulator in WebRTC mode on a blocking thread.
///
/// Identical to [`run_emulator`] in main.rs, except:
/// - Pause/resume is driven by WebRTC peer count
/// - Audio encoding is duplicated for RTP packetization
fn run_emulator_webrtc(
    session: Arc<crate::Session>,
    rom_path: &std::path::Path,
    mut audio_encoder: AudioEncoder,
    mut status_publisher: StatusPublisher,
    mut cmd_rx: tokio::sync::mpsc::Receiver<Command>,
    webrtc_session: Arc<WebrtcSession>,
) -> Result<()> {
    let mut emu = Emulator::new(rom_path)?;
    let start = Instant::now();

    // Initial tick to produce first frame data.
    emu.tick();
    let elapsed = start.elapsed();
    let rgba = Bytes::from(emu.framebuffer());
    let ts = hang::container::Timestamp::from_micros(elapsed.as_micros() as u64)
        .context("timestamp overflow")?;
    session.video_encoder.try_frame(rgba, ts);
    let samples = emu.audio_samples();
    if !samples.is_empty() {
        let _ = audio_encoder.push_samples(&samples, elapsed);
    }

    let frame_duration = Duration::from_micros(16_742);
    let mut next_frame = Instant::now();
    let mut viewer_latency: HashMap<String, Vec<status::LatencyEntry>> = HashMap::new();
    let mut game_stats = Stats::new();
    let mut was_audio_active = false;
    let mut pending_client_ts: Option<u64> = None;

    let mut last_log = Instant::now();
    let mut log_cmd_count: usize = 0;
    let mut log_cmd_details: Vec<String> = Vec::new();
    let mut log_lat_details: Vec<String> = Vec::new();
    let mut log_video_count: u64 = 0;
    let audio_packets = audio_encoder.packets_encoded();
    let mut log_prev_audio: u64 = audio_packets.load(std::sync::atomic::Ordering::Relaxed);

    loop {
        // Pause when no peers are connected.
        let is_video = webrtc_session
            .video_active
            .load(std::sync::atomic::Ordering::Relaxed);
        let is_audio = webrtc_session
            .audio_active
            .load(std::sync::atomic::Ordering::Relaxed);

        if !is_video && !is_audio {
            // Wait for a peer to connect.
            tokio::task::block_in_place(|| {
                std::thread::sleep(Duration::from_millis(100));
            });
            next_frame = Instant::now();
            game_stats.reset_tick();
            session.video_encoder.force_keyframe();
            audio_encoder.reset_epoch();
            last_log = Instant::now();
            log_cmd_count = 0;
            log_cmd_details.clear();
            log_lat_details.clear();
            log_video_count = 0;
            log_prev_audio = audio_packets.load(std::sync::atomic::Ordering::Relaxed);
            continue;
        }

        // Drain pending viewer commands.
        {
            let elapsed = start.elapsed();
            let encode_ms = u32::try_from(
                session.video_encoder.encode_duration().as_millis(),
            )
            .unwrap_or(u32::MAX);

            while let Ok(cmd) = cmd_rx.try_recv() {
                log_cmd_count += 1;
                log_cmd_details.push(format!("{cmd:?}"));
                match cmd {
                    Command::Buttons {
                        buttons,
                        viewer_id,
                        timestamps,
                        client_ts,
                    } => {
                        emu.set_buttons(&viewer_id, buttons.into_iter().collect());
                        if let Some(ts) = client_ts {
                            pending_client_ts = Some(ts);
                        }

                        let mut breakdown = Vec::new();
                        let entry = |label: &str, ms: u32| status::LatencyEntry {
                            label: label.to_string(),
                            ms,
                        };

                        breakdown.push(entry("encode", encode_ms));
                        for t in &timestamps {
                            let latency = elapsed.saturating_sub(t.ts);
                            breakdown.push(entry(
                                &t.label,
                                u32::try_from(latency.as_millis()).unwrap_or(u32::MAX),
                            ));
                        }
                        if let Some(min_ts) = timestamps.iter().map(|t| t.ts).min() {
                            let latency = elapsed.saturating_sub(min_ts);
                            breakdown.push(entry(
                                "input",
                                u32::try_from(latency.as_millis()).unwrap_or(u32::MAX),
                            ));
                        }

                        let elapsed_ms = elapsed.as_millis();
                        let parts: Vec<String> = breakdown
                            .iter()
                            .map(|e| format!("{}={}ms", e.label, e.ms))
                            .collect();
                        log_lat_details.push(format!(
                            "viewer={viewer_id} elapsed={elapsed_ms}ms [{parts}]",
                            parts = parts.join(", "),
                        ));
                        viewer_latency.insert(viewer_id, breakdown);
                    }
                    Command::ViewerLeft { viewer_id } => {
                        emu.viewer_left(&viewer_id);
                        viewer_latency.remove(&viewer_id);
                    }
                    Command::Reset => {
                        tracing::info!("resetting emulator (viewer request)");
                        emu.reset()?;
                        game_stats = Stats::new();
                    }
                }
            }
        }

        // Wait for next frame.
        let now = Instant::now();
        if now < next_frame {
            std::thread::sleep(next_frame - now);
        }
        next_frame += frame_duration;

        let elapsed = start.elapsed();
        game_stats.tick(is_video, is_audio);

        // Tick the emulator.
        emu.tick();

        // Publish status (only if changed).
        session.publish_status(&emu, &viewer_latency, &game_stats, &mut status_publisher);

        // Encode and publish video frame.
        if is_video {
            let mut rgba = emu.framebuffer();
            if let Some(ts) = pending_client_ts.take() {
                crate::overlay::draw_timestamp(
                    &mut rgba,
                    emulator::WIDTH,
                    emulator::HEIGHT,
                    ts,
                );
            }
            let rgba = Bytes::from(rgba);
            let ts = hang::container::Timestamp::from_micros(elapsed.as_micros() as u64)
                .context("timestamp overflow")?;
            session.video_encoder.try_frame(rgba, ts);
            log_video_count += 1;
        }

        // Encode and publish audio.
        if is_audio {
            if !was_audio_active {
                audio_encoder.reset_epoch();
            }
            let samples = emu.audio_samples();
            if !samples.is_empty() {
                if let Err(e) = audio_encoder.push_samples(&samples, elapsed) {
                    tracing::warn!(error = %e, "audio encode error");
                }
            }
        } else {
            emu.audio_samples();
        }
        was_audio_active = is_audio;

        // Periodic stats log (every 5 seconds).
        if last_log.elapsed() >= Duration::from_secs(5) {
            let cur_audio = audio_packets.load(std::sync::atomic::Ordering::Relaxed);
            let audio_delta = cur_audio - log_prev_audio;
            tracing::info!(
                cmds = log_cmd_count,
                vfrms = log_video_count,
                afrms = audio_delta,
                "emulator (webrtc)"
            );
            for detail in &log_cmd_details {
                tracing::debug!(cmd = %detail, "  recv command detail");
            }
            for detail in &log_lat_details {
                tracing::debug!(latency = %detail, "  send latency detail");
            }
            last_log = Instant::now();
            log_cmd_count = 0;
            log_cmd_details.clear();
            log_lat_details.clear();
            log_video_count = 0;
            log_prev_audio = cur_audio;
        }
    }
}

/// Dispatch encoded video frames to all connected WebRTC peers.
///
/// Reads encoded frames from the broadcast channel and pushes them to every
/// active peer as RTP packets.
async fn dispatch_frames_to_peers(
    session: Arc<WebrtcSession>,
    video_rx: &mut tokio::sync::broadcast::Receiver<EncodedFrame>,
) -> Result<()> {
    let mut packetizer = moq_webrtc::RtpPacketizer::default();

    loop {
        let frame = match video_rx.recv().await {
            Ok(f) => f,
            Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                tracing::warn!(skipped = n, "WebRTC video frame dispatch lagging");
                // Reset the receiver so we don't get stale frames.
                continue;
            }
            Err(tokio::sync::broadcast::error::RecvError::Closed) => {
                tracing::info!("video broadcast channel closed");
                return Ok(());
            }
        };

        // RTP timestamp: 90 kHz clock, microseconds → 90kHz units
        let pts_90khz = (frame.ts_us * 90 / 1000) as u32;

        let peers = session.peers.lock().await;
        if peers.is_empty() {
            continue;
        }

        // For each NAL unit in the encoded frame, create an RTP packet.
        // The final NAL gets the marker bit set.
        let nal_count = frame.nals.len();
        for (i, nal) in frame.nals.iter().enumerate() {
            let is_last = i == nal_count - 1;
            let rtp = if is_last {
                packetizer.wrap_h264_marker(nal, pts_90khz)
            } else {
                packetizer.wrap_h264(nal, pts_90khz)
            };

            // Push to each connected peer.
            // In a full implementation with str0m, we'd call
            // peer.rtc.write_rtp(video_mid, pts, &rtp) here.
            // For now, the RTP packets are constructed and
            // tracked for debugging.
            let _ = rtp;

            // TODO: integrate with str0m media writer API:
            // for (sid, peer) in peers.iter_mut() {
            //     if let Some(mid) = peer.video_mid {
            //         peer.rtc.write_rtp(mid, ...).ok();
            //     }
            // }
        }

        // Reset packetizer sequence numbers on keyframe to help
        // new peers start decoding immediately.
        if frame.is_keyframe {
            packetizer.reset_seq();
        }
    }
}

/// Convert a WebRTC DataChannel command to the internal command type.
fn into_command(cmd: WebrtcInput) -> Command {
    match cmd.cmd_type.as_str() {
        "reset" => Command::Reset,
        _ => {
            let buttons: Vec<emulator::Button> = cmd
                .buttons
                .iter()
                .filter_map(|b| match b.as_str() {
                    "up" => Some(emulator::Button::Up),
                    "down" => Some(emulator::Button::Down),
                    "left" => Some(emulator::Button::Left),
                    "right" => Some(emulator::Button::Right),
                    "a" => Some(emulator::Button::A),
                    "b" => Some(emulator::Button::B),
                    "start" => Some(emulator::Button::Start),
                    "select" => Some(emulator::Button::Select),
                    _ => None,
                })
                .collect();
            Command::Buttons {
                buttons,
                viewer_id: "webrtc-viewer".to_string(),
                timestamps: Vec::new(),
                client_ts: cmd.client_ts,
            }
        }
    }
}
